language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - 51101661@qq.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- export BUILD_NAME=authserver-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
env:
  global:
  - secure: RYs/SPiHq711WGitY7fJAQqu4xcLujifz/fy93QEXx1SmdpuscgPY0BOXYShQzg0vayEpJBwzNNV/8/OjLWRn4Ge8p3Cq4AC5J4YbCmFb9wax5BfqvKrVpqhAzqOocCYP6CoIm1JI8vX3kFjAC1x8RjrQdizFIrDX/h9qW4jqRWVxPDS0ohqJK+HuLFbmGCBdy7gJy2szWs3mZLYpACG8aReXHha7Iy5tWE4kSqVqqB7kDyrD9AOtX0HQe0o5Fh8lloK/qSBIfwnxhP/qY5k1Zhkte1X8RcEUkjAiZo3+L+A2m8Io3hNgYin31viuZpQxOCgO+cS3AcmW797AOMnDBmZ407HhRARMrpL+cyNSk0uGKzuWpmkicaZm3aI50BbcwtjBWARxx+d3Hn/+5XQbjjTzQ5PD5NSER+TEJXxaDx9FEvhHiAwCzYqP/aqxbQE5LZfl1RT9lQsMnjudhVX9yee3c02b7UwTEoNR3j4vUefSwgYR4L02TxJt5eoXGeAV0SokfUz2xTikTYec8Y9jVTB99XjW25Zmsc/WKBn+sU2ZslBMkEXiTJ4Xo9FzwUcvgKT3NGL7s9OD7czTD5A5M6PAxUaCOVmePhzqplyUqg/R2IjecmybT9fAgv6Jo5yOwKa5hovzgugKki86RJL+8COlK48+JlTXoLWeYidH5I=
  - secure: ckwfm+GMCeCLtfioKma3H5un0fymkJ2VosgBAHEcgz6eSa3Naim4pFvjjUhRRyg36nhYlbQORhzdD6lWNLcjB9xTU1erMD9VEcW5PA9VP4LW9eIw8AhCCiEeGYHmZ4W5dQhqrOY0tnJ05xiC218z2/mHE4jtkievFpleh33SZTsLA+IC1zAVVLbhdHbv2wfHGbfGJRkuu0497E4sKcU1FTmmQPyh+7nYcRuy4OGqKpWz3BMWUxMuCTx7MXtC66CjMZvGk1Af9MiskpgsLYupkkZIVupVTylrpCNRJGXNHkT78z/y0tj1oCFzo69hPg9wF4M7nSMFCfyZ5OeV3Yjz7KgtkaeCNLc72gVn6rtC6hZoVsVd5kYKfm3enLjLpJYTXadMnBucnstodUkhrgSd7cvX2dSKDXyZme2rvbfDj8JnruZoTrxh3BXOv0ym7mU70NgD5hucz29CDX/OJlbhCuRdhaZgOGINCaZCE1zkSUJ9tKaZtNI2730VhCPWUxnoPdttYJVkv0k7494Kw++mk1ZrtzFPD0YpEu3oHgj2x4s7zFXMOKpqPDTYlWHlRSdtTnp/XjN3kwLPZALCULVdzSoDtAl+IBJHg7c8PSOKnqyZTws55sJSeMirY1EjtO+IN98/gi4FEOHuyomgTMHiz3rJ08gp5XQ2dGXh6nfwcYs=
  - secure: NrZdT+zIWvQe9TNFPCiigAolaCURDB8QC3f7Gx9/6VdMm/5kzko8UvI3HMqhyC0wk0q16rIXu/fy4gngYDJNLj0pKO+30U+d89IIDvT7JIWhUMgf6Wt3aHQ6NJpy/6CGcfq5zgRKfv/ByWMO42EOYRk2HRvyDbUNDNqYjmXYZGUPRtKU51eBBlzK6xkJ5mn5EYCFT3nd6pvkHLvb03IsuVkEhk2CGQQgDNtiZs3TrUG1GtHac04SMlS7J70s4qiqp/T43wrfPFNgqu6TvfFE4XLnFd8hYRBNfc8UcDqZgFl38ts0VE83RSe47oiw9Oamcp2okkxeFrLMuT8USKbufILrFrdyJ9KKifWvSmJT0lv54XFZziXg7iRTtxW0mBCtbHn31KLLw/zKGusji34VBd86xzsqamNaFexxVIyPZ+hdGKVlKZltGgblcADGGCA3zXy+i3lsj6KdQhRnGxTi32czWlwMDe3xjpJsWfpoPU12uPesABseOJmFcwbWAneVwo8/M2MiyrBWLU59ntR7lUzolWZ0tDAo4TZAhqCVW5+Vj20yngfBDXP0R1KKD1ZReJvJdv/t82rPnSEiOCxXqfO/NFEBecWR1NCcgsedHIuCcQbBWDKVAGNab318TosNJMvUiNXx7dITteEiy/o+jERKlny2irwTtq4nsLGl8Vw=
